### ISSUE TITLE
Популярные личности на главной

### ISSUE THREAD

**Issue by ramm** [66ru/gpor-docs#2]
Нужна документация:

```
можно узнать подробней об алгоритме вывода популярных личностей
```

**Comment by stepanoff** [comment]
https://github.com/mediasite/gpor-docs/wiki/%D0%9F%D0%BE%D0%BF%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D1%8B%D0%B5-%D0%BB%D0%B8%D1%87%D0%BD%D0%BE%D1%81%D1%82%D0%B8-%D0%BD%D0%B0-%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B9
